import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import Navbar from './components/Navbar';
import store from '../redux/store';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

export default function Home() {

  const router = useRouter()
  useEffect(() =>{
    router.push("/agents");
  },[])

  return (
    <>
    <Head>
        <title>Next Store App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className={styles.container}>
      <h1>Welcome to Store</h1>
    </div>
    </>
  )
}
